baseURL = 'https://traversable-dale.github.io/'
languageCode = 'en-us'
title = 'John Syzonenko'
theme = "hugo-theme-console"

[params]
  description = "Creative Technologist specializing in immersive installations"
  customCSS = ["css/custom.css"]
  
  # Change the cursor character
  cursor = "●"  # Dot
  
  # Or try these alternatives:
  # cursor = "▮"  # Tall block
  # cursor = "▯"  # Hollow block
  # cursor = "_"  # Underscore
  # cursor = "|"  # Pipe
  # cursor = "█"  # Block cursor (default)
  # cursor = "●"  # Dot
  # cursor = "►"  # Triangle
  # cursor = "»"  # Double angle


[[params.navlinks]]
  name = "Home"
  url = "/"

[[params.navlinks]]
  name = "About"
  url = "/about/"

[[params.navlinks]]
  name = "Work"
  url = "/work/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[taxonomies]
  tag = "tags"
  category = "categories"


  